"""
Layer8 <-> Access console client.

Connects this desktop program's sign-in to the web admin control panel
(access/api/v1/verify.php). A user created in the web console signs in here
with their email + access key; the website controls them (suspend / revoke /
expire / seat limits / version floor / maintenance), and those decisions take
effect at the program's next check-in.

Security model (from the console's HANDOFF Part 3):
  - Every answer from the server is Ed25519-signed. We verify the signature
    against the PUBLIC key baked in below, over a canonical string built from
    OUR nonce and OUR device id (never the echoed ones). An unsigned or
    tampered or replayed answer is treated as DENIED.
  - Decisions are made only from the SIGNED fields (status/reason), never the
    HTTP code, which a proxy or captive portal can change.
  - Offline grace: the last allowed answer may keep the program running until
    its valid_until, unless the clock was wound back.

Ports the reference client in HANDOFF Part 3; canonical() and trusted() are
byte-for-byte the parts that must be exact.
"""

import base64
import json
import os
import secrets
import time
import urllib.error
import urllib.request
from datetime import datetime, timezone
from pathlib import Path

try:
    from nacl.exceptions import BadSignatureError
    from nacl.signing import VerifyKey
    _HAVE_NACL = True
except Exception:  # pragma: no cover - PyNaCl missing
    _HAVE_NACL = False

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

# The server's PUBLIC signing key (base64). Safe to ship. Generated by the
# console's make-keys.php. If the server's key pair is ever regenerated, this
# must be updated to match or every answer will read as untrusted.
PUBLIC_KEY = "Zamm4Ac+/NdZAmr+Akugw6dHuIydSljfJRgdEaLbvQE="

# Where the console answers. Production is https on the live host; local
# testing uses the XAMPP dev server. Override with the L8_ACCESS_API_URL env
# var (used for testing against http://localhost:8080/...).
API_URL = os.environ.get(
    "L8_ACCESS_API_URL",
    "https://hatchtag.dev/access/api/v1/verify.php",
)

# Reported to the server and compared against the console's "oldest allowed
# version". Keep in step with the app's real version.
APP_VERSION = os.environ.get("L8_APP_VERSION", "1.4.3")

# Per-install state (device id, last good answer, clock high-water mark).
_STATE_DIR = Path(os.environ.get("LOCALAPPDATA", str(Path.home()))) / "Layer8"
_DEVICE_FILE = _STATE_DIR / "device.uid"
_GRACE_FILE = _STATE_DIR / "access_state.json"


# ---------------------------------------------------------------------------
# Per-install identity and state
# ---------------------------------------------------------------------------

def get_device_uid() -> str:
    """A stable id for THIS install: 'dev_' + 16 random hex chars, made once
    and stored. Not a hardware serial (privacy, and it must survive hardware
    swaps but not survive a reinstall)."""
    try:
        _STATE_DIR.mkdir(parents=True, exist_ok=True)
        if _DEVICE_FILE.exists():
            uid = _DEVICE_FILE.read_text(encoding="utf-8").strip()
            if 8 <= len(uid) <= 64 and uid.replace("_", "").replace("-", "").isalnum():
                return uid
        uid = "dev_" + secrets.token_hex(8)  # 16 hex chars
        _DEVICE_FILE.write_text(uid, encoding="utf-8")
        return uid
    except Exception:
        # Fall back to an ephemeral id if the disk is not writable. It will
        # take a new seat each run, but sign-in still works.
        return "dev_" + secrets.token_hex(8)


def _device_name() -> str:
    return (os.environ.get("COMPUTERNAME")
            or os.environ.get("HOSTNAME")
            or "Unknown device")[:120]


# ---------------------------------------------------------------------------
# Signature verification - MUST be exact (HANDOFF Part 3)
# ---------------------------------------------------------------------------

def canonical(r: dict, nonce: str, device_uid: str) -> str:
    """The exact string the server signed: fixed fields, fixed order, joined
    by '|', empty string for null. nonce and device_uid are OURS - never the
    echoed ones - so an answer captured for another request or machine fails."""
    def s(v):
        return "" if v is None else str(v)
    user = r.get("user") or {}
    return "|".join([
        "acc-v" + s(r.get("v")),
        s(r.get("status")),
        s(r.get("reason")),
        s(user.get("id")),
        s(user.get("plan")),
        s(r.get("expires_at")),
        s(r.get("valid_until")),
        s(r.get("recheck_after")),
        s(r.get("issued_at")),
        nonce,
        device_uid,
    ])


def trusted(r: dict, nonce: str, device_uid: str) -> bool:
    """True only if this answer was Ed25519-signed by the server for THIS
    request. Unsigned answers are always refused."""
    if not _HAVE_NACL:
        return False
    sig = r.get("sig")
    if not sig:
        return False
    try:
        VerifyKey(base64.b64decode(PUBLIC_KEY)).verify(
            canonical(r, nonce, device_uid).encode("utf-8"),
            base64.b64decode(sig),
        )
        return True
    except (BadSignatureError, ValueError, TypeError):
        return False


# ---------------------------------------------------------------------------
# Online sign-in
# ---------------------------------------------------------------------------

def sign_in(email: str, access_key: str, device_uid: str = None,
            device_name: str = None) -> dict:
    """Ask the console. Returns:
        {'allowed': bool, 'reason': str, 'message': str,
         'answer': dict|None, 'nonce': str|None}
    'reason' is 'offline' if the server was unreachable, 'untrusted' if the
    answer failed signature verification."""
    device_uid = device_uid or get_device_uid()
    device_name = device_name or _device_name()
    nonce = secrets.token_hex(16)  # fresh and random for EVERY request

    body = json.dumps({
        "email": email,
        "access_key": access_key,
        "device_uid": device_uid,
        "device_name": device_name,
        "app_version": APP_VERSION,
        "nonce": nonce,
    }).encode("utf-8")

    req = urllib.request.Request(API_URL, data=body, method="POST",
                                 headers={"Content-Type": "application/json"})
    try:
        with urllib.request.urlopen(req, timeout=15) as resp:
            raw = resp.read()
    except urllib.error.HTTPError as e:
        raw = e.read()  # 401/403/429/503 still carry a signed JSON answer
    except (urllib.error.URLError, TimeoutError, OSError):
        return {"allowed": False, "reason": "offline",
                "message": "Could not reach the access server.", "answer": None, "nonce": None}

    try:
        r = json.loads(raw)
    except ValueError:
        return {"allowed": False, "reason": "untrusted",
                "message": "The server's answer was not readable.", "answer": None, "nonce": None}

    if not trusted(r, nonce, device_uid):
        return {"allowed": False, "reason": "untrusted",
                "message": "The server's answer could not be verified.", "answer": None, "nonce": None}

    # Decide on the SIGNED fields only. 'message'/user['name'] are display-only.
    allowed = r.get("status") == "allowed" and r.get("reason") == "ok"
    result = {"allowed": allowed, "reason": r.get("reason"),
              "message": r.get("message", ""), "answer": r, "nonce": nonce}

    if allowed:
        _save_grace(r, nonce, device_uid)
    elif r.get("reason") == "revoked":
        _forget_grace()  # revoked: forget the stored key/answer
    return result


# ---------------------------------------------------------------------------
# Offline grace
# ---------------------------------------------------------------------------

def _save_grace(answer: dict, nonce: str, device_uid: str) -> None:
    try:
        _STATE_DIR.mkdir(parents=True, exist_ok=True)
        latest = max(time.time(), _load_grace().get("latest_seen", 0))
        _GRACE_FILE.write_text(json.dumps({
            "answer": answer, "nonce": nonce,
            "device_uid": device_uid, "latest_seen": latest,
        }), encoding="utf-8")
    except Exception:
        pass


def _load_grace() -> dict:
    try:
        return json.loads(_GRACE_FILE.read_text(encoding="utf-8"))
    except Exception:
        return {}


def _forget_grace() -> None:
    try:
        _GRACE_FILE.unlink(missing_ok=True)
    except Exception:
        pass


def still_valid_offline(device_uid: str = None) -> bool:
    """On a launch with no network: may the program run on its last good answer?
    Verifies the saved signature, checks status/valid_until, and refuses if the
    clock was wound back below the highest time ever seen (5-min tolerance)."""
    device_uid = device_uid or get_device_uid()
    saved = _load_grace()
    r = saved.get("answer")
    if not r or not trusted(r, saved.get("nonce", ""), device_uid):
        return False
    now = time.time()
    if now < saved.get("latest_seen", 0) - 300:  # clock wound back
        return False
    try:
        until = datetime.strptime(r["valid_until"], "%Y-%m-%dT%H:%M:%SZ").replace(tzinfo=timezone.utc)
    except (KeyError, ValueError):
        return False
    # keep raising the high-water mark
    if now > saved.get("latest_seen", 0):
        saved["latest_seen"] = now
        try:
            _GRACE_FILE.write_text(json.dumps(saved), encoding="utf-8")
        except Exception:
            pass
    return r.get("status") == "allowed" and now < until.timestamp()


# ---------------------------------------------------------------------------
# High-level gate used by the app's login
# ---------------------------------------------------------------------------

# What each denial means for the UI (short, safe to show; the server also
# sends its own 'message' which is preferred when present).
REASON_TEXT = {
    "invalid_credentials": "That email and access key do not match.",
    "suspended":       "Your access has been suspended. Contact the administrator.",
    "revoked":         "Your access has been revoked.",
    "expired":         "Your access has expired. Contact the administrator to renew.",
    "seat_limit":      "All of your device seats are in use. Remove a device from the console.",
    "version_too_old": "This version is too old. Please update the program.",
    "rate_limited":    "Too many attempts. Please wait a few minutes and try again.",
    "maintenance":     "Sign-in is paused for maintenance. Please try again shortly.",
    "not_connected":   "The access server is not set up yet.",
    "bad_request":     "The program sent an invalid request (please report this).",
    "offline":         "Could not reach the access server. Check your connection.",
    "untrusted":       "The server's answer could not be verified.",
}


def _user_of(answer: dict) -> dict:
    """The signed user block: {'id', 'name', 'plan'} (name is display-only)."""
    return (answer or {}).get("user") or {}


def check_access(email: str, access_key: str) -> dict:
    """Gate the app's sign-in against the website.

    Tries the server first. If the server is unreachable, falls back to a valid
    offline grace answer. Returns:
        {'allowed': bool, 'reason': str, 'message': str, 'offline': bool,
         'name': str, 'plan': str}
    """
    email = (email or "").strip().lower()
    device_uid = get_device_uid()
    res = sign_in(email, access_key, device_uid=device_uid)

    if res["reason"] == "offline":
        # No network: honour a still-valid, signed grace answer.
        if still_valid_offline(device_uid):
            u = _user_of(_load_grace().get("answer"))
            return {"allowed": True, "reason": "offline_grace",
                    "message": "Working offline on your saved access.", "offline": True,
                    "name": u.get("name", email), "plan": u.get("plan", "")}
        msg = res["message"] or REASON_TEXT.get("offline", "Offline.")
        return {"allowed": False, "reason": "offline", "message": msg, "offline": True,
                "name": "", "plan": ""}

    u = _user_of(res.get("answer"))
    msg = res["message"] or REASON_TEXT.get(res["reason"], "Access denied.")
    return {"allowed": res["allowed"], "reason": res["reason"], "message": msg,
            "offline": False, "name": u.get("name", email), "plan": u.get("plan", "")}


if __name__ == "__main__":
    # Manual test:  python access_client.py email key
    import sys
    if len(sys.argv) >= 3:
        out = check_access(sys.argv[1], sys.argv[2])
        print(f"device_uid : {get_device_uid()}")
        print(f"api_url    : {API_URL}")
        print(f"allowed    : {out['allowed']}")
        print(f"reason     : {out['reason']}")
        print(f"message    : {out['message']}")
    else:
        print("usage: python access_client.py <email> <access_key>")
        print(f"device_uid: {get_device_uid()}")
        print(f"api_url   : {API_URL}")
